image: go1.3
git:
  path: github.com/stefscherer/go-hello-again
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - go build
publish:
    github:
        branch: master
        script:
          - mkdir release
          - cp go-hello-again release/
        artifacts:
          - release/
        tag: v$(cat VERSION)
        token: {{TOKEN}}
        user: stefscherer
        repo: go-hello-again
notify:
  email:
    recipients:
      - scherer_stefan@icloud.com
